on:
  push:
    tags:
      - v*

name: Ensure amalgamation is up to date

jobs:
  test:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup LDC
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - name: Build (to fetch dependencies)
        run: dub build
      - name: Copy current amalgamation
        run: cp ./single-file/jcli.d ./single-file/jcli-branch.d
      - name: Run amalgamator
        run: |
          cd ./tools/amalgamator
          dub run
          cd ../../
      - name: Ensure files are the same
        run: cmp ./single-file/jcli.d ./single-file/jcli-branch.d