on: [push, pull_request]

name: Test Examples

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        dc: [ldc-latest]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: "Run tests"
        shell: pwsh
        run: cd ./examples/; dub run --single ./test.d